# Bubble Sort

In [32]:
import numpy as np
arr=np.array([2,34,-4,23,75])
temp=0
print("before sorting  ",arr)
for i in range(len(arr)-1):
        for j in range(len(arr)-1-i):
            if arr[j]>arr[j+1]:
                temp = arr[j]
                arr[j]=arr[j+1]
                arr[j+1]=temp
print("after sorting  ",arr)                

before sorting   [ 2 34 -4 23 75]
after sorting   [-4  2 23 34 75]


# Second Method for Bubble Sort in limited loops

In [44]:
import numpy as np
arr=np.array([1,2,4,3,5,6])
temp=0
fflag=False
print("before sorting  ",arr)
for i in range(len(arr)-1):
        for j in range(len(arr)-1-i):
            if arr[j]>arr[j+1]:
                temp = arr[j]
                arr[j]=arr[j+1]
                arr[j+1]=temp
                fflag=True
                print("number of loops for sorting: ",j)
        if(not fflag):
            break
            
print("after sorting  ",arr)                


before sorting   [1 2 4 3 5 6]
number of loops for sorting:  2
after sorting   [1 2 3 4 5 6]


# Sorting in string Array 

In [51]:
arr=np.array(["Athar","Ashir","Asghar"])
temp=0
print("before sorting  ",arr)
for i in range(len(arr)-1):
        for j in range(len(arr)-1-i):
            if arr[j][1]>arr[j+1][1]: #sorting in ascending depending upon first letter of word due to 0 index which we have mentioned
                temp = arr[j]
                arr[j]=arr[j+1]
                arr[j+1]=temp
print("before sorting  ",arr)

before sorting   ['Athar' 'Ashir' 'Asghar']
before sorting   ['Ashir' 'Asghar' 'Athar']


# Selection Sort

In [59]:
arr=np.array([2,5,2,7,5,99,34,65,99])
temp=0
print("before sorting  ",arr)
for i in range(len(arr)-1):
    index=i
    for j in range(i+1,len(arr)): #this loop is for finding smallest value in aa
        if arr[j]<arr[index]: 
                index=j
                
    if arr[i]!=arr[index]:
        temp=arr[i]
        arr[i]=arr[index]
        arr[index]=temp
            
print("after sorting   ",arr)

before sorting   [ 2  5  2  7  5 99 34 65 99]
after sorting    [ 2  2  5  5  7 34 65 99 99]


# Insertion Sort

In [76]:
#this compares values with its left ones 
arr=np.array([34,21,87,54,63,3])
temp=0
print("before sorting  ",arr)
print()
print()
for i in range(1,len(arr)):
    temp=arr[i]
    index=i
    
    while(index != 0 and arr[index-1 > temp]):
        arr[index]=arr[index-1]
        index-=1
    arr[index]=temp
   
    print("Sorting   ",arr)

print()
print()
print("after sorting   ",arr)

print("loop = ",i)

before sorting   [34 21 87 54 63  3]


Sorting    [34 21 87 54 63  3]
Sorting    [21 34 87 54 63  3]
Sorting    [87 21 34 54 63  3]
Sorting    [54 87 21 34 63  3]
Sorting    [63 54 87 21 34  3]
Sorting    [ 3 63 54 87 21 34]


after sorting    [ 3 63 54 87 21 34]
loop =  5


# Counting Sort

In [2]:
#step 1 ==> same range ka alag array aur usmn sy uski index wise value nikali aur doosri array k us value index mn inc krdi
#step 2 ==> values previous values sy sum hota jaega
#step 3 ==> original array sy value uthao phr ussi value k index-1 pe jao new array k 
          # aur unsorted array me us value ka ek decrement krdo.. ye kam range aur zyada values k array k liye best use hai

In [9]:
import numpy as np
arr=np.array([5,3,2,5,3,1,7])
count=np.array([0 for i in range(10)])

#count each value of arr and store it in count array
for i in range(len(arr)):
    count[arr[i]]+=1
print(count)

print()
print()
# modify count array by sum of previous value
for i in range(1,len(count)):
    count[i]+=count[i-1]
print(count)


# create another for place sorting values
sortedArr=np.array([0 for i in range(len(arr))])

print()
print()
# placing values
for i in range(len(arr)):
    sortedArr[count[arr[i]]-1] = arr[i]
    count[arr[i]]-=1
    print(sortedArr)


[0 1 1 2 0 2 0 1 0 0]


[0 1 2 4 4 6 6 7 7 7]


[0 0 0 0 0 5 0]
[0 0 0 3 0 5 0]
[0 2 0 3 0 5 0]
[0 2 0 3 5 5 0]
[0 2 3 3 5 5 0]
[1 2 3 3 5 5 0]
[1 2 3 3 5 5 7]


# Counting Sort with values > 20

In [14]:
arr=np.array([29,22,25,23,22,25])
minn=arr[0]
maxx=arr[0]

for i in range(len(arr)):
    if(minn>arr[i]):
        minn=arr[i]
    if(maxx<arr[i]):
        maxx=arr[i]

count=np.array([0 for i in range((maxx-minn)+1)])

for i in range(len(arr)):
    count[arr[i]-minn]+=1
    
    
for i in range(len(count)):
    print(count[i],end=" ")
print()


for i in range(1,len(count)):
    count[i]+=count[i-1]

    
for i in range(1,len(count)):
    print(count[i],end=" ")

    
sortedArr=np.array([0 for i in range(len(arr))])

print()
print()
# placing values
for i in range(len(sortedArr)):
    sortedArr[count[arr[i]-minn]-1] = arr[i]
    count[arr[i]-minn]-=1
    print(sortedArr)

2 1 0 2 0 0 0 1 
3 3 5 5 5 5 6 

[ 0  0  0  0  0 29]
[ 0 22  0  0  0 29]
[ 0 22  0  0 25 29]
[ 0 22 23  0 25 29]
[22 22 23  0 25 29]
[22 22 23 25 25 29]


# Optimized code without modify count array

In [15]:
arr=np.array([29,22,25,23,22,24])
minn=arr[0]
maxx=arr[0]

for i in range(len(arr)):
    if(minn>arr[i]):
        minn=arr[i]
    if(maxx<arr[i]):
        maxx=arr[i]

count=np.array([0 for i in range((maxx-minn)+1)])

for i in range(len(arr)):
    count[arr[i]-minn]+=1

sortedArr=np.array([0 for i in range(len(arr))])

k=0
for i in range(len(count)):
    for j in range(count[i],0,-1):
        sortedArr[k]=i+minn
        k+=1
        
for i in range(len(sortedArr)):
    print(sortedArr[i],end=" ")
    

22 22 23 24 25 29 