# Exercise 5.1

In [6]:
lowerbound = int(input("Enter starting range: "))
upperbound = int(input("Enter ending range: "))
chances=5
for i in range(chances-1):
    mid = int((upperbound - lowerbound)/2 + lowerbound) #Linear Search method
    print("guessed: ",mid)
    print(chances-i-1," chances left")
    guess = input(" Where to go? Enter Higher or Lower? and Enter C if guessed correct ::>  ")
    if guess == 'higher':
        lowerbound = mid
    elif guess == 'lower':
        upperbound = mid
    elif guess == 'c':
        print( 'Game over. Machine Won! secret number was: ' + str(mid))
        break
    else:
        print('Wrong input nigga')
        break

    

Enter starting range: 1
Enter ending range: 16
guessed:  8
4  chances left
 Where to go? Enter Higher or Lower? and Enter C if guessed correct ::>  higher
guessed:  12
3  chances left
 Where to go? Enter Higher or Lower? and Enter C if guessed correct ::>  higher
guessed:  14
2  chances left
 Where to go? Enter Higher or Lower? and Enter C if guessed correct ::>  lower
guessed:  13
1  chances left
 Where to go? Enter Higher or Lower? and Enter C if guessed correct ::>  c
Game over. Machine Won! secret number was: 13


# Exercise 5.2

In [9]:
import numpy as np
x=np.array([0 for i in range(3)])
y=np.array([0 for i in range(3)])
for i in range(3):
    x[i]=int(input(f"Enter {i+1} element value: "))
for j in range(3):
    y[j]=int(input(f"Enter {j+1} element value: "))
    
print(x)
print(y)

z=np.array([0 for i in range(3)])
for i in range(3):
    temp=x[i]
    for j in range(3):
        if(temp==y[j]):
            z[j]+=1
print(z)

Enter 1 element value: 1
Enter 2 element value: 1
Enter 3 element value: 2
Enter 1 element value: 1
Enter 2 element value: 2
Enter 3 element value: 3
[1 1 2]
[1 2 3]
[2 1 0]
