# Lab: 3 
# Exercise:1

In [3]:
for i in range(1,10):
    for j in range(1,10):
        print(j*i,end=' ')
    print()

1 2 3 4 5 6 7 8 9 
2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 
9 18 27 36 45 54 63 72 81 


# Lab: 3 
# Exercise: 2

In [194]:
import numpy as np
a=[' ','        Period 1 ','Period 2 ','Period 3 ','Period 4 ']
b=['Monday','   PF','       PF','       OFF','      OFF']
c=['Tuesday','  ICT','      ICT','      OFF','      OFF']
d=['Wednesday','OFF','      OFF','      PIS','      PIS']
e=['Thursday',' VLM','      VLM','      PF Lab','   PF Lab']
f=['Friday','   OFF','      OFF','      ICT Lab','  ICT Lab']
x=np.array([a,b,c,d,e,f])
x

array([[' ', '        Period 1 ', 'Period 2 ', 'Period 3 ', 'Period 4 '],
       ['Monday', '   PF', '       PF', '       OFF', '      OFF'],
       ['Tuesday', '  ICT', '      ICT', '      OFF', '      OFF'],
       ['Wednesday', 'OFF', '      OFF', '      PIS', '      PIS'],
       ['Thursday', ' VLM', '      VLM', '      PF Lab', '   PF Lab'],
       ['Friday', '   OFF', '      OFF', '      ICT Lab', '  ICT Lab']],
      dtype='<U17')

# Lab: 3 
# Exercise: 3

In [103]:
m1=np.array([[1,2,3,4],[5,6,7,8]])
m2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
result = [[0,0,0,],
         [0,0,0,],
         ]

for i in range(len(m1)):

    for j in range(len(m2[0])):
        for k in range(len(m2)):
            result[i][j] += m1[i][k] * m2[k][j]
for r in result:
    print(r)

[70, 80, 90]
[158, 184, 210]


# Lab: 3 
# Exercise: 4

In [294]:
x=np.array([[1,2,3],[4,5,6],[9,8,9]])
d1=0
d2=0
for i in range(0,3):
    for j in range(0,3):
        
        # First diagonal 
        if (i == j): 
            d1 += x[i][j] 
  
        # 2nd diagonal 
        if (i == 3 - j-1 ): 
            d2 += x[i][j]
result= d1-d2
print(x)
print("Answer => ",result)

[[1 2 3]
 [4 5 6]
 [9 8 9]]
Answer =>  -2


# Lab: 3 
# Exercise: 5

In [318]:
x=np.array([[0 for i in range(7)]for j in range(3)])
d1=0
d2=0
d3=0
for i in range(3):
    for j in range(7):
               x[i][j]= input(f"Enter monkey number {i+1}'s {j+1} day food: ")
for i in range(3):
    for j in range(7):
        if(i==0):
            d1+=x[i][j]
        elif(i==1):
            d2+=x[i][j]
        elif(i==2):
            d3+=x[i][j]
if(d1>d2 and d1>d3):
    print("Monkey 1 has eaten huge amount of food ",d1)
elif(d2>d1 and d2>d3):
    print("Monkey 2 has eaten huge amount of food ",d2)
elif(d3>d2 and d3>d1):
    print("Monkey 3 has eaten huge amount of food ",d3)

    
if(d1<d2 and d1<d3):
    print("Monkey 1 has eaten least amount of food ",d1)
elif(d2<d1 and d2<d3):
    print("Monkey 2 has eaten least amount of food ",d2)
elif(d3<d2 and d3<d1):
    print("Monkey 3 has eaten least amount of food ",d3)

    
if((d1>d2 or d1>d3) and (d1<d3 or d1<d2)):
    print("Monkey 1 has eaten average amount of food ",d1)
elif((d2>d1 or d2>d3) and (d2<d3 or d2<d1)):
    print("Monkey 2 has eaten average amount of food ",d2)
elif((d3>d2 or d3>d1) and (d3<d1 or d3<d2)):
    print("Monkey 3 has eaten average amount of food ",d3)


Enter monkey number 1's 1 day food: 32
Enter monkey number 1's 2 day food: 32
Enter monkey number 1's 3 day food: 34
Enter monkey number 1's 4 day food: 56
Enter monkey number 1's 5 day food: 345
Enter monkey number 1's 6 day food: 34
Enter monkey number 1's 7 day food: 345
Enter monkey number 2's 1 day food: 34
Enter monkey number 2's 2 day food: 34
Enter monkey number 2's 3 day food: 65
Enter monkey number 2's 4 day food: 324654
Enter monkey number 2's 5 day food: 3342
Enter monkey number 2's 6 day food: 3243
Enter monkey number 2's 7 day food: 43
Enter monkey number 3's 1 day food: 32
Enter monkey number 3's 2 day food: 54
Enter monkey number 3's 3 day food: 234
Enter monkey number 3's 4 day food: 45
Enter monkey number 3's 5 day food: 65
Enter monkey number 3's 6 day food: 76
Enter monkey number 3's 7 day food: 3
Monkey 2 has eaten huge amount of food  331415
Monkey 3 has eaten least amount of food  509
Monkey 1 has eaten average amount of food  878


# Lab: 3
# Exercise: 6

In [2]:
import numpy as np
x=np.array([[[0 for i in range(7)]for j in range(2)] for k in range(7)])
#x = np.zeros((2, 2, 2))
for i in range(7):
    for j in range(2):
        for k in range(7):
            x[i][j][k]=input(f"Enter student {i+1} score of part {j+1} of exam {k+1}: ")
            
            
d1=0
d2=0
d3=0
d4=0
d5=0
d6=0
d7=0


for i in range(7): 
    for j in range(2):
        for k in range(7):
            if(i==0):
                d1+=x[i][j][k]
            elif(i==1):
                d2+=x[i][j][k]
            elif(i==2):
                d3+=x[i][j][k]
            elif(i==3):
                d4+=x[i][j][k]
            elif(i==4):
                d5+=x[i][j][k]
            elif(i==5):
                d6+=x[i][j][k]
            elif(i==6):
                d7+=x[i][j][k]
print()
print("********* RESULT *********")
print()
print("Students 1 total marks: ",d1)
print("Students 2 total marks: ",d2)
print("Students 3 total marks: ",d3)
print("Students 4 total marks: ",d4)
print("Students 5 total marks: ",d5)
print("Students 6 total marks: ",d6)
print("Students 7 total marks: ",d7)

Enter student 1 score of part 1 of exam 1: 7
Enter student 1 score of part 1 of exam 2: 8
Enter student 1 score of part 1 of exam 3: 9
Enter student 1 score of part 1 of exam 4: 8
Enter student 1 score of part 1 of exam 5: 6
Enter student 1 score of part 1 of exam 6: 6
Enter student 1 score of part 1 of exam 7: 5
Enter student 1 score of part 2 of exam 1: 6
Enter student 1 score of part 2 of exam 2: 56
Enter student 1 score of part 2 of exam 3: 76
Enter student 1 score of part 2 of exam 4: 5
Enter student 1 score of part 2 of exam 5: 7
Enter student 1 score of part 2 of exam 6: 45
Enter student 1 score of part 2 of exam 7: 65
Enter student 2 score of part 1 of exam 1: 4
Enter student 2 score of part 1 of exam 2: 7
Enter student 2 score of part 1 of exam 3: 8
Enter student 2 score of part 1 of exam 4: 5
Enter student 2 score of part 1 of exam 5: 45
Enter student 2 score of part 1 of exam 6: 34
Enter student 2 score of part 1 of exam 7: 6
Enter student 2 score of part 2 of exam 1: 8
Ente