# Exercise 1.1

In [2]:
balance=50000
limit=30000
while(True):
    x=int(input("Enter amount: "))
    if x>balance or x>=limit:
        print("sorry you dont have that much amount: ")
    elif x>limit:
        print("sorry you have only 30000 limit: ")
    elif balance<5000:
        tax=(balance/100)*2
        balance-=tax
        print("2% tax has been deducted from your account: ")
        print(f"You have {balance} remaining in your account: ")
    elif balance>=5000:
        print("no tax deducted")
        balance-=x
        print("Remaining balance = ",balance)
        break
#print("Remaining balance = ",balance)

Enter amount: 12000
no tax deducted
Remaining balance =  38000


# Exercise 1.2

In [32]:
count=0
x=int(input("Enter numbers: "))
while x != 0:
    x//=10
    count+=1
print("total numbers: ",count)

Enter numbers: 4534543534
total numbers:  10


# Exercise 1.3

In [29]:
x=int(input("Enter item price: "))
y=int(input("Enter item quantity: "))
bill=x*y
print("your total bill = ",bill)
if bill>500:
    disc=int(bill/100)*10
    print(f"You received discount of {disc}")
    print(f"Pay {bill-disc} only")

Enter item price: 450
Enter item quantity: 5
your total bill =  2250
You received discount of 220
Pay 2030 only


# Exercise 1.4

In [27]:
cost=int(input("Enter cost of buying: "))
sell=int(input("Enter cost of selling: "))
if cost>sell:
    print("you are in loss of ",cost-sell)
elif cost<sell:
    print("you are in profit of ",sell-cost)
elif cost==sell:
    print("no profit or loss ")

Enter cost of buying: 200
Enter cost of selling: 11
you are in loss of  189


## Exercise 1.5

In [24]:
days=int(input("Enter days: "))
if days>0 and days<=5:
    print("50 rupees fine")
elif days>5 and days<=10:
    print("100 rupees fine")
elif days>10 and days<=30:
    print("150 rupees fine")
elif days>30:
    print("Membership cancelled")

Enter days: 45
Membership cancelled


# Exercise 1.6

In [23]:
x=int(input("Enter a num: "))
fact=1
if x<0:
    print("Enter a positive integar")
elif x==0:
    print("factorial of 0 is 1")
else:
    for i in range(1,x+1):
        fact *= i
    print(f"factorial of {x} is {fact}")

Enter a num: 6
factorial of 6 is 720


# Exercise 1.7

In [16]:
x=int(input("Enter fibonacci series number: "))
n1,n2 =0,1
count=0
if x<=0:
    print("Enter a positive integar nigga: ")
elif x==1:
    print("Fibonacci series upto ",x)
else:
    print("Fibonacci series: ")
    while count<x:
        print(n1)
        nth=n1+n2
        #updating values
        n1=n2
        n2=nth
        count+=1

Enter fibonacci series number: 12
Fibonacci series: 
0
1
1
2
3
5
8
13
21
34
55
89


# Exercise 1.8

In [11]:
for x in range(2,9):
    for y in range(1,8):
        if y==x:
            break
        else:
            print(y,end=" ")
    for z in range(8,1,-1):
        if z==x:
            break
        else:
            print(end="*")
    print()

1 ******
1 2 *****
1 2 3 ****
1 2 3 4 ***
1 2 3 4 5 **
1 2 3 4 5 6 *
1 2 3 4 5 6 7 


#  Exercise 1.9

In [9]:
star="*****"
x=int(input("Enter a number for printing times of stars: "))
for i in range(x):
    print(star,end="\n")
    

Enter a number for printing times of stars: 6
*****
*****
*****
*****
*****
*****


# Exercise 1.10

In [6]:
x=np.arange(10)
for i in range(10):
    y=input(f" enter marks of student {i+1}: ")
    x[i]=y
print("==============================")
mx=0
mn = 100
ag=0
for j in range(len(x)):
        if x[j] > mx:
            ag += x[j]
            mx = x[j]
        elif x[j] < mn:
            ag += x[j]
            mn = x[j]
            
print(f"max = {mx}")
print(f"min = {mn}")
print(f"avg = {ag/10}")

 enter marks of student 1: 44
 enter marks of student 2: 55
 enter marks of student 3: 66
 enter marks of student 4: 77
 enter marks of student 5: 88
 enter marks of student 6: 99
 enter marks of student 7: 45
 enter marks of student 8: 34
 enter marks of student 9: 23
 enter marks of student 10: 65
max = 99
min = 23
avg = 53.1


# Exercise 1.11

In [2]:
import numpy as np
firstArray=np.array([0 for i in range(5)])
length=len(firstArray)

for i in range(length):
    firstArray[i]=i+1
for j in(firstArray):
    print(firstArray)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


# Exercise 1.12

In [5]:
N = int(input("How Many Players Name You Want To Enter: "))
names=np.array([' ' for i in range(N)],dtype=object)
for j in range(len(names)):
    print()
    names[j]=input(f"Enter {j+1} Player Name: ")
print("=========OUTPUT=========")
for k in(names):
    print(k,end=" ")

How Many Players Name You Want To Enter: 5

Enter 1 Player Name: harry

Enter 2 Player Name: alex

Enter 3 Player Name: danny

Enter 4 Player Name: miller

Enter 5 Player Name: shawn
=========OUTPUT=========
harry alex danny miller shawn 