# Exercise 4.1 Bubble Sort

In [9]:
import numpy as np
import time

array = np.array([4,3,9,3,1])
count = 0
print("Original Array : ")
print(array)
print()
print()
for i in range(len(array)-1):
    flag = False
    for j in range(len(array)-1-i):
        if array[j] > array [j+1]:
            temp = array[j]
            array[j] = array[j+1]
            array[j+1] = temp
            flag = True
            count +=1
            print(array ," step ",count)
    
    if(not flag):
        break
print()
print()
print("Sorted Array: ")
print(array)
print()
print()
print("Total Swappings : ",count)


if __name__ == '__main__':
    start = time.clock()

    elapsed = (time.clock() - start)
    print("Time taken for bubble sort = ", elapsed)

Original Array : 
[4 3 9 3 1]


[3 4 9 3 1]  step  1
[3 4 3 9 1]  step  2
[3 4 3 1 9]  step  3
[3 3 4 1 9]  step  4
[3 3 1 4 9]  step  5
[3 1 3 4 9]  step  6
[1 3 3 4 9]  step  7


Sorted Array: 
[1 3 3 4 9]


Total Swappings :  7
Time taken for bubble sort =  0.00010120000001734297


C:\Users\athar\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\athar\Anaconda3\lib\site-packages\ipykernel_launcher.py:35: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead


# Exercise 4.2 Selection Sort

In [12]:
array = np.array([4,3,9,3,1])
count = 0
print("Original Array : ")
print(array)
print()
print()


for i in range(len(array)-1):
    index = i
    for j in range(i+1,len(array)):
        if array[j] < array[index]:
            index = j
    if array[i] != array[index]:
        temp = array[i]
        array[i] = array[index]
        array[index] = temp
        count +=1
        print(array ," step ",count)
    
    if(not flag):
        break
print()
print()
print("Sorted Array: ")
print(array)
print()
print()
print("Total Swappings : ",count)


if __name__ == '__main__':
    start = time.clock()

    elapsed = (time.clock() - start)
    print("Time Taken For Selection Sort = ", elapsed)

Original Array : 
[4 3 9 3 1]


[1 3 9 3 4]  step  1
[1 3 3 9 4]  step  2
[1 3 3 4 9]  step  3


Sorted Array: 
[1 3 3 4 9]


Total Swappings :  3
Time Taken For Selection Sort =  0.00025750000008883944


C:\Users\athar\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\athar\Anaconda3\lib\site-packages\ipykernel_launcher.py:35: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
